### ISSUE TITLE
app_meetme

### ISSUE THREAD

**Issue by ldcsirtest2012** [ugoviti/izpbx#28]
Docker file
   --enable app_meetme \
    --disable app_ivrdemo \
    --disable app_meetme \

I would appreciate it if you could increase app_meetme to new image    The asterisk confbridge not work will at channelredirect ,so I need use meetme 
Thanks

**Comment by ugoviti** [comment]
Hi,
as I was using app_confbridge for conferences so I doesn't noted that before...

Anyway If not wrong app_meetme will be deprecated by app_confbridge:

```
MeetMe conference bridge                                                                
                                                                                        
    Depends on: dahdi(E)                                                                
       Can use: N/A                                                                     
Conflicts with: N/A                                                                     
 Support Level: extended, Replaced by: app_confbridge, Deprecated in: 19, Removed in: 21
```

as I can see app_meetme depend on chan_dahdi, but chan_dahdi is't supported by izPBX (correct me if I'm wrong)

of course let's me know if you find a way to compile app_meetme, reopen this issue.

Kind Regards

**Comment by ldcsirtest2012** [comment]
when make dahdi   kernel-devel kernel verison  must be same 
yum install "kernel-devel-uname-r == $(uname -r)

**Comment by ugoviti** [comment]
Right, but the izPBX container should can run un every host kernel version, how can follow the outside kernel version?
