### ISSUE TITLE
MySQL TLS/SSL Support?

### ISSUE THREAD

**Issue by AshleyJackson** [ugoviti/izpbx#32]
Hello.

Have you considered the possibility of implementing support for database connections that require TLS/SSL ?

While obviously this is not critical, it would be a "nice to have".

Thanks for your time.

**Comment by ugoviti** [comment]
Hi,

I haven't tried, but since this is a FreePBX related job, if you configure FreePBX to connect to MySQL database via TLS, it doesn't works?

Let's me know if I must change some config.

Kind Regards
