### ISSUE TITLE
[after 18.16.13 upgrade] dnsmasq: cannot access directory /etc/dnsmasq.d: Permission denied

### ISSUE THREAD

**Issue by Karmak23** [ugoviti/izpbx#34]
Hello,

For my personnal install (home) I used `izdock/izpbx-asterisk:18.16.9` a while ago, and everything went smoothy. I used TFTP but not DHCP since I already have a router doing the job. The whole container worked as expected, I have phones working, external trunk, etc.

After upgrading to `18.16.13` (docker-compose pull, merge .env and docker-compose.yml), the `izpbx` container keeps booting/halting infinitely, because /etc/dnsmasq.d seems out of reach.

But I didn't change anything on the storage side.

I tried changing permissions on [local host volume] `./data/izpbx/etc/dnsmasq.d`, giving it to my user account launching the container, giving it back to root, chmod it 777… Nothing changes. I need to deactivate TFTP for the container to stay alive.

What should I look for to debug this issue ? What could have gone wrong on the local host for this to fail ?
Thanks for your help,

**Comment by ugoviti** [comment]
Hi, until I verify that bug can you rollback to 18.16.9? simply put the version in the image tag of your docker-compose.yml

thank you

**Comment by ugoviti** [comment]
can you attach the log of the `docker logs izpbx` while boot looping?

Thankyou

**Comment by Karmak23** [comment]
Sorry for the delay, I have been completely flooded by my business. I will get back to you on the rollback and log ASAP, it's on my todo list.
