### ISSUE TITLE
VoIP XML PhoneBook Lookup problem

### ISSUE THREAD

**Issue by accept** [ugoviti/izpbx#39]
Hi

I am using DeepL translation as I am Japanese and not fluent in English.
I apologize if the meaning is not understood or if there are any rude phrases.

I tried to access "http://PBX_ADDRESS/pb" as described in the readme, but it seems that the address described inside the xml is the internal address of Docker (probably for bridging with izpbx-db).
Line 116 of entrypoint-hooks.sh

`$(hostname -I | awk '{print $1}')`

This one.

`$(hostname -I | awk '{print $2}')`

If I change this to this, I can get the correct external address (LAN address), but I think this is the result because my environment uses izpbx-ext.

I didn't see anything specific in the readme, etc. Is this expected behavior?
Also, is the only way to get around this is to put the LAN address in the APP_FQDN, etc.?

**Comment by accept** [comment]
It is very unfortunate that you choose to ignore them.
We will modify the script to suit our environment and use it.
Thanks for providing a great product.

**Comment by ugoviti** [comment]
Hi, 

have you tried to change that configuration option in you `.env` file?

```
### PhoneBook Settings
## PhoneBook server address used by VoiP Phones.
## You can specify IP or DNS name. If empty, by default will be used in order: 'http://$APP_FQDN' or 'http://PBXIP'
#PHONEBOOK_ADDRESS=https://izpbx.example.com
```

Kind regards

**Comment by accept** [comment]
Thank you for your reply.
I did not know that there were PhoneBook Settings in .env, but I read the shell script and understood that if $APP_FQDN was defined, that would be used.
I am currently handling it that way, but will use PhoneBook Settings from now on.

I wanted to know if it is an expected behavior that the shell script cannot get the IP address for external use unless the IP address is manually written in the .env when configured using macvlan instead of bridge.

If this is the expected behavior and it means that the IP address must be specified manually when using macvlan, then no problem.
However, if this is not the expected behavior, I asked if it is expected or not, considering the possibility of other problems that may occur together.

Now, I wish I could have told you earlier, but the izPBX you built is working great at one of our clinics in Japan.
For privacy reasons, I can't give you the details here, but it has really helped us by reducing the amount of work we have to do on the phone every day.
I am truly grateful for that.
Thank you very much.
As the year 2023 is just around the corner, I wish you a happy New Year.
I wish Mr. ugoviti a wonderful year.
