### ISSUE TITLE
How to fix "No swap"

### ISSUE THREAD

**Issue by tungtouch** [ugoviti/izpbx#42]
Hello,
I deploy success, but i see an issue with "no swap".

<img width="533" alt="image" src="https://user-images.githubusercontent.com/7944776/222394485-d513cbd3-0253-49b1-8c21-a36d3cabe651.png">

Then i use the steps bellow to fix it, but not working:

1. sudo docker compose -it izbpx /bin/bash
2. sudo fallocate -l 2G /swapfile
3. sudo chmod 600 /swapfile
4. sudo mkswap /swapfile
5. sudo swapon /swapfile
The error here > swapon: /swapfile: swapon failed: Invalid argument

<img width="778" alt="image" src="https://user-images.githubusercontent.com/7944776/222395141-e272f654-8d98-421c-86f2-c85ae9828928.png">

I don't know how to fix it. Please help me! thanks

**Comment by ugoviti** [comment]
Hi, 

you can just add swap space in your host server (outside docker)

example:

```
dd if=/dev/zero of=/.swap bs=1M count=2048
mkswap /.swap
echo "/.swap swap swap defaults 0 0" >> /etc/fstab
chmod 0600 /.swap
swapon -a
```

and then restart izpbx container:

`docker restart izpbx`

Kind regards

**Comment by tungtouch** [comment]
> 

Well, thats working! Thank you so much.

**Comment by ugoviti** [comment]
Thank you for the feedback.

Kind Regards

**Comment by tungtouch** [comment]
When i use your guide, its works for me.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/7944776/222423198-fcc99920-cb22-4c2b-99e3-5edcd2868eb9.png">

But in the dashboard, I still see error "no swap" even though I restarted docker and restarted VPS.
<img width="565" alt="image" src="https://user-images.githubusercontent.com/7944776/222423094-3a8763e2-38ff-46da-91a3-cd26591d1d0b.png">
