### ISSUE TITLE
Multi-Tenant VoIP PBX with shared global Database and single docker-compose.yml file

### ISSUE THREAD

**Issue by michaelfangtw** [ugoviti/izpbx#43]
in the multi-tenant's docker-compose.yml  sample:
   env_file:
    - db.env

env_file = db.env    id not working,  shows error below,    after change env_file to .env  , it works well.
maybe it has some problem in mariadb's docker file to read the [env_file] for enviornment variable.

docker logs show error:
[ERROR] [Entrypoint]: Database is uninitialized and password option is not specified
        You need to specify one of MARIADB_ROOT_PASSWORD, MARIADB_ROOT_PASSWORD_HASH, MARIADB_ALLOW_EMPTY_ROOT_PASSWORD and MARIADB_RANDOM_ROOT_PASSWORD

**Comment by ugoviti** [comment]
Hi, what is the content of your db.dev file?

inside this file you must place the MYSQL variables, like:

```db.env
MYSQL_ROOT_PASSWORD=39oidl6GT9ZebMtjq2heJV747EIs
```

Kind Regards

**Comment by michaelfangtw** [comment]
db.env 's content is the same with  .env
and I check the variable of mysql_root_password id the default value that I didn't change it
(MYSQL_ROOT_PASSWORD=CHANGEM3)

did I need to  change it to work ??

**Comment by ugoviti** [comment]
I don't know the root cause of your problem. Anyway, using .env file you solved the problem?

**Comment by ugoviti** [comment]
Happy to know that, thank you for your reply.
