### ISSUE TITLE
Image Size > 3GB

### ISSUE THREAD

**Issue by hobbit378** [ugoviti/izpbx#44]
Followed the official build recipe in https://github.com/ugoviti/izpbx/tree/main/izpbx-asterisk for 'Asterisk 20 + FreePBX 16' ; ended up with a docker image of 3.12GB as opposed to the (uncompressed) 1.43GB of your official build in docker hub.
Any ideas/advise on how to bring the image size down (missing build switches/args ...?)

**Comment by ugoviti** [comment]
Hi,

yes, by default using the suggested build command you make a "devel" build with asterisk and freepbx in place.

just set APP_DEBUG=0 in the command build, ex.

```
docker build --pull --rm --build-arg APP_DEBUG=0 --build-arg APP_VER_BUILD=1 --build-arg APP_BUILD_COMMIT=0000000 --build-arg APP_BUILD_DATE=$(date +%s) --build-arg APP_VER=dev-20.16 --build-arg ASTERISK_VER=20.0.0 --build-arg FREEPBX_VER=16 -t izpbx-asterisk:dev-20.16 .
```

Kind Regards
