### ISSUE TITLE
FreeBBX not starting when ipv6 enabled on system.

### ISSUE THREAD

**Issue by vaska94** [ugoviti/izpbx#59]
Hello, I have tested only on latest version, FreePBX doesn't start if I have Ipv6 address enabled and ipv6 address in /etc/hosts, removing it helps. any ideas how to fix without disabling ipv6?
I don't use ipv6 but its little bit inconvenient

**Comment by ugoviti** [comment]
Hi, what host Operating System are you using?

**Comment by vaska94** [comment]
Rocky 9

**Comment by vaska94** [comment]
Simply removing 
`::1 localhost `
from `/etc/hosts` file, solves the issue. but i don't understand why it conflicts with izpbx!

**Comment by ugoviti** [comment]
have you made other tests with IPv6?

**Comment by vaska94** [comment]
I'm simply disabling Ipv6 on all servers using `grubby --update-kernel ALL --args ipv6.disable=1`
have not found any other solution.
