### ISSUE TITLE
issue freepbxuser 

### ISSUE THREAD

**Issue by grinono** [ugoviti/izpbx#61]
The mysql admin user is creating the freepbxuser.

But that user is not able to start the service. It looks like the IP from where the user is created from does align with the public ip.

izpbx  |   SQLSTATE[HY000] [1045] Access denied for user 'freepbxuser'@'10.22.125.123'  
izpbx  |    (using password: YES)   

any idea how to fix this? the changing the IP or setting % does not seem to work.

**Comment by grinono** [comment]
fixed it

**Comment by LeoASIR** [comment]
what was the error? Can you help me and tell me how you solved it?

**Comment by LeoASIR** [comment]
> fixed it

what was the error? Can you help me and tell me how you solved it?
