### ISSUE TITLE
Question about my environment

### ISSUE THREAD

**Issue by nstp11** [ugoviti/izpbx#63]
Hi repo! Thank you very much for your project! Meticulous work.

While building your image, I ran into some probably minor problems, the biggest one was caused by [this line]( https://github.com/ugoviti/izpbx/blob/99c19ceb7acdeeced5ed9f15dfceed0aff724711/izpbx-asterisk/Dockerfile#L440C1-L440C147).

The error seemed quite strange to me. After a couple of hours, I finally found the problem: my system had strange configurations and the build process was unable to download and validate the ASTERISK package from the official github.com's release page, but the build process continued. 

I remembered that I configured a public proxy to hide my public ip and also to increase my security; unfortunately, after disabling that proxy, the problem was still there. After other three hours (!), I finally discovered that also my DNS system had strange settings and the domain github.com was pointing to another server. 

At that point I was really exhausted and said: "That's enough! I can't build this image here! It looks like a production image and I need to find another build server."

My friend has a `gitlab-worker` installed on his raspberry, so I asked him to build your image there and he was happy to help me.

I would like to follow your updates to keep my system up-to-date, but I don't want to contact my friend every time I need to build an image.

As a starting point, I would ask if there is a way to validate if the downloaded package is ok, at least `asterisk-*.tar.gz`, before continuing with the process.

Do you think this is a problem only in my environment and I should just check my settings before building images?

**Comment by ugoviti** [comment]
Hi, are you still experiencing this issue?

Kind regards
