### ISSUE TITLE
Asterisk doesn't start with default settings

### ISSUE THREAD

**Issue by Ali-Dogan** [ugoviti/izpbx#67]
Hello I'm following installation guide and using default configurations for docker-compose but I'm getting following errors and Asterisk doesn't start and can't access WEB UI. Any help appreciated.

[Apr 30 11:37:17] Asterisk 20.7.0 built by root @ 66a836815c95 on a x86_64 running Linux on 2024-04-10 21:17:05 UTC
[Apr 30 11:37:17] NOTICE[1079] loader.c: 336 modules will be loaded.
[Apr 30 11:37:17] ERROR[1079] config.c: The file 'extensions_override_freepbx.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:17] ERROR[1079] config.c: The file 'res_odbc_custom.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:17] WARNING[1079] res_odbc.c: Unable to load config file res_odbc.conf
[Apr 30 11:37:17] ERROR[1079] config_options.c: Unable to load config file 'cdr.conf'
[Apr 30 11:37:17] NOTICE[1079] cdr.c: Failed to process CDR configuration; using defaults
[Apr 30 11:37:17] NOTICE[1079] cdr.c: CDR simple logging enabled.
[Apr 30 11:37:17] NOTICE[1079] dnsmgr.c: Managed DNS entries will be refreshed every 300 seconds.
[Apr 30 11:37:17] ERROR[1079] config.c: The file 'features_general_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:17] ERROR[1079] config_options.c: Contents of features.conf are invalid and cannot be parsed
[Apr 30 11:37:17] NOTICE[1079] features_config.c: Could not load features config; using defaults
[Apr 30 11:37:17] ERROR[1079] config.c: The file 'http_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:17] NOTICE[1079] indications.c: Default country for indication tones: us
[Apr 30 11:37:17] NOTICE[1079] indications.c: Setting default indication country to 'us'
[Apr 30 11:37:17] ERROR[1079] config.c: The file 'udptl_custom.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:17] ERROR[1079] config_options.c: Contents of udptl.conf are invalid and cannot be parsed
[Apr 30 11:37:17] NOTICE[1079] udptl.c: Could not load udptl config; using defaults
[Apr 30 11:37:18] WARNING[1079] res_musiconhold.c: No music on hold classes configured, disabling music on hold.
[Apr 30 11:37:18] ERROR[1079] config.c: The file 'rtp_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:18] NOTICE[1079] res_smdi.c: No SMDI interfaces are available to listen on, not starting SMDI listener.
[Apr 30 11:37:18] ERROR[1079] config.c: The file 'iax_general_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:18] ERROR[1079] chan_iax2.c: Config file iax.conf is in an invalid format.  Aborting.
[Apr 30 11:37:18] ERROR[1079] config.c: The file 'sip_general_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:18] ERROR[1079] chan_sip.c: Contents of sip.conf are invalid and cannot be parsed
[Apr 30 11:37:18] ERROR[1079] message.c: No 'sip' message technology found.
[Apr 30 11:37:18] ERROR[1079] ari/config.c: No configured users for ARI
[Apr 30 11:37:18] NOTICE[1079] confbridge/conf_config_parser.c: Adding default_menu menu to app_confbridge
[Apr 30 11:37:18] WARNING[1079] cdr_csv.c: unable to load config: cdr.conf
[Apr 30 11:37:18] WARNING[1079] app_voicemail.c: maxsilence should be less than minsecs or you may get empty messages
[Apr 30 11:37:18] ERROR[1079] chan_dongle.c: Errors reading config file dongle.conf, Not loading module
[Apr 30 11:37:18] ERROR[1079] config.c: The file 'http_additional.conf' was listed as a #include but it does not exist.
[Apr 30 11:37:18] WARNING[1079] loader.c: Some non-required modules failed to load.
[Apr 30 11:37:18] WARNING[1079] loader.c: Module 'app_macro' has been loaded but was deprecated in Asterisk version 16 and will be removed in Asterisk version 21. Its replacement is 'app_stack (GoSub)'.
[Apr 30 11:37:18] ERROR[1079] loader.c: Error loading module 'res_pjsip_phoneprov_provider.so', missing dependency: res_phoneprov
[Apr 30 11:37:18] ERROR[1079] loader.c: pbx_config declined to load.
[Apr 30 11:37:18] ERROR[1079] loader.c: res_odbc declined to load.
[Apr 30 11:37:18] ERROR[1079] loader.c: Declined modules which depend on res_odbc: res_config_odbc, cdr_adaptive_odbc, cdr_odbc, cel_odbc, func_odbc
[Apr 30 11:37:18] ERROR[1079] loader.c: chan_sip declined to load.
[Apr 30 11:37:18] ERROR[1079] loader.c: cdr_csv declined to load.
[Apr 30 11:37:18] ERROR[1079] loader.c: chan_dongle declined to load.

**Comment by ugoviti** [comment]
can you repeat the test with latest release 20.16.15?

Kind regards
