### ISSUE TITLE
How deploy with not default APP_PORT_MYSQL?

### ISSUE THREAD

**Issue by allcho** [ugoviti/izpbx#68]
Hi.
 I tried use APP_PORT MYSQL=3308, because in my server port 3306 is busy
But I get this error

![Снимок экрана от 2024-05-15 12-19-03](https://github.com/ugoviti/izpbx/assets/11857812/1d44a620-82ee-4e8c-8110-c812b9b69724)
Whats I do wrong?  In addition to this port, I also change this port APP_PORT_HTTP. All other settings are by default

**Comment by ugoviti** [comment]
Hi, there is an already opened bug report in the FreePBX Issue Tranking and there aren't solutions right now if not using other IP with the 3306 ports:

reported in the ChangeLog:

## [20.16.4] - 2023-02-04
### Changed
- Updated PBX engine to Asterisk `20.1.0` LTS (https://downloads.asterisk.org/pub/telephony/asterisk/releases/ChangeLog-20.1.0)
### Fixed
- Fixed unable to use custom MySQL port than 3006 (partial fix #40. FreePBX related problem: ref. https://issues.freepbx.org/browse/FREEPBX-24066)


I seen the old issue traking is been changed, so I can't recover the original Issue.

If you can, fill a new issue in the https://github.com/FreePBX/issue-tracker/issues new portal.

Thank you
