### ISSUE TITLE
Multi-Tenant VoIP PBX with shared global Database and single compose.yml file

### ISSUE THREAD

**Issue by anildalar** [ugoviti/izpbx#75]
![WhatsApp Image 2024-06-27 at 1 34 18 PM](https://github.com/ugoviti/izpbx/assets/25725857/e7fa4544-8be4-4aa9-9be4-25a9500d403f)

I have successly deployed the Multi-Tenant VoIP PBX with shared global Database and single compose.yml file with SSL

**Comment by ugoviti** [comment]
Hi,

Why FreePBX 15? what version of izpbx are you running?
