### ISSUE TITLE
How to access phpmyadin  /admin/pma not working

### ISSUE THREAD

**Issue by rohitmali123** [ugoviti/izpbx#80]
It Shows forbedden.

I have enabled 
PMA_ENABLED=true 
in .env file

**Comment by ugoviti** [comment]
Hi, 

do you enabled the following options?

```
### phpMyAdmin
PMA_ALIAS=/admin/pma
PMA_ALLOW_FROM=127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
PMA_ENABLED=true
```

Kind regards

**Comment by ugoviti** [comment]
closing... let's me know if I can repeat your issue.

Kind regards
