### ISSUE TITLE
I can't Login to freePBX ajaxRequest declined - Referrer

### ISSUE THREAD

**Issue by allcho** [ugoviti/izpbx#83]
Hello
Today I tried Login to freepbx and got error ajaxRequest declined - Referrer
I see in browser network this POST admin/ajax.php?command=navbarToogle getting 403 Forbiden
Whats wrong? 
Can you help me?

**Comment by AmjedKhaled165** [comment]
try this
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by allcho** [comment]
that my logs
![Снимок экрана от 2024-09-19 16-22-29](https://github.com/user-attachments/assets/504752c5-7561-4325-ac6f-027eeb293b6b)

**Comment by allcho** [comment]
> Hi, still having this issue?

Hi, I solved this by restoring from last day's backup.

**Comment by ugoviti** [comment]
Thank you for the feedback.

Kind regards
