### ISSUE TITLE
Can't access FreePBX gui

### ISSUE THREAD

**Issue by masterBrog** [ugoviti/izpbx#84]
Hi,
I realise I'm almost certainly being a complete noob... but how do you get to the FreePBX GUI?? The default .env suggests its on port 80 and `netstat` seems to suggest httpd is hosting up port 80. but I don't get anything back on my host machine when I visit localhost:80. Also don't get anything when I exec in and `wget localhost`. and nothing in `/etc/httpd/logs/access_logs`. But `httpd` process looks like it's running ok.

Container logs don't seem untoward in any way. 

I'm guessing I'm missing something... but could you give me some pointers?
All the best

**Comment by ugoviti** [comment]
Thank you for the feedback.

Kind regards
