### ISSUE TITLE
Crashes on Synology DSM 7.2 Container Manager on startup

### ISSUE THREAD

**Issue by skyynet** [ugoviti/izpbx#85]
Starting the image on my Synology RS818+ in Container Manager first informs, that variable APP_FQDN is not set. I don't know what to enter there and removed the variable definition.

Maybe i'm naive, but I assumed, I don't have to configure anything before running and config will be done in GUI later.

Startup gives errors and then stops the image.

Log

2024/10/31 21:22:03 | stdout | ---> WARNING: unable to access asterisk database. Please check if exist and the permissions... exiting
2024/10/31 21:22:03 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:22:03 | stdout | ---> START install FreePBX @ Thu Oct 31 20:22:03 UTC 2024
2024/10/31 21:22:03 | stdout | --> installing FreePBX in '/var/www/html'
2024/10/31 21:22:03 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:22:03 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[10/10]
2024/10/31 21:22:03 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:58 | stdout | /usr/sbin/safe_asterisk: line 171:  1282 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:53 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[9/10]
2024/10/31 21:21:53 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:52 | stdout | /usr/sbin/safe_asterisk: line 171:  1203 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:46 | stdout | /usr/sbin/safe_asterisk: line 171:  1124 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:43 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[8/10]
2024/10/31 21:21:43 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:39 | stdout | /usr/sbin/safe_asterisk: line 171:  1047 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:33 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[7/10]
2024/10/31 21:21:33 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:33 | stdout | /usr/sbin/safe_asterisk: line 171:   968 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:26 | stdout | /usr/sbin/safe_asterisk: line 171:   891 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:23 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[6/10]
2024/10/31 21:21:23 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:20 | stdout | /usr/sbin/safe_asterisk: line 171:   812 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:14 | stdout | /usr/sbin/safe_asterisk: line 171:   733 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:13 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[5/10]
2024/10/31 21:21:13 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:07 | stdout | /usr/sbin/safe_asterisk: line 171:   656 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:21:03 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[4/10]
2024/10/31 21:21:03 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:21:01 | stdout | /usr/sbin/safe_asterisk: line 171:   577 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:55 | stdout | /usr/sbin/safe_asterisk: line 171:   498 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:53 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[3/10]
2024/10/31 21:20:53 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:20:48 | stdout | /usr/sbin/safe_asterisk: line 171:   421 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:43 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[2/10]
2024/10/31 21:20:43 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:20:42 | stdout | /usr/sbin/safe_asterisk: line 171:   342 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:36 | stdout | /usr/sbin/safe_asterisk: line 171:   265 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:33 | stdout | Asterisk Started
2024/10/31 21:20:29 | stdout | /usr/sbin/safe_asterisk: line 171:   180 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:20:27 | stdout | STARTING ASTERISK
2024/10/31 21:20:27 | stdout |  
2024/10/31 21:20:27 | stdout |  
2024/10/31 21:20:27 | stdout | --> NOTE: skipping MySQL init because not root user password defined
2024/10/31 21:20:27 | stdout | --> missing '/.initialized' file... initializing FreePBX... try:[1/5]
2024/10/31 21:20:27 | stdout | =====================================================================
2024/10/31 21:20:27 | stdout | => !!! NEW INSTALLATION DETECTED :: FreePBX IS NOT INITIALIZED !!! <=
2024/10/31 21:20:27 | stdout | =====================================================================
2024/10/31 21:20:27 | stdout |  
2024/10/31 21:20:27 | stdout | ---> configuring FreePBX ODBC
2024/10/31 21:20:27 | stdout | ---> verifing FreePBX configurations
2024/10/31 21:20:27 | stdout | --> configuring izpbx service...
2024/10/31 21:20:27 | stdout | => Enabling izpbx service... because IZPBX_ENABLED=true
2024/10/31 21:20:27 | stdout | => Disabling asterisk service... because ASTERISK_ENABLED=false
2024/10/31 21:20:27 | stdout | --> configuring Apache VirtualHosting and creating empty /etc/httpd/conf.d/virtual.conf file
2024/10/31 21:20:27 | stdout | --> setting Apache ServerName to izPBX
2024/10/31 21:20:27 | stdout | --> configuring httpd service...
2024/10/31 21:20:27 | stdout | => Enabling httpd service... because HTTPD_ENABLED=true
2024/10/31 21:20:27 | stdout | --> reconfiguring Fail2ban settings...
2024/10/31 21:20:27 | stdout | --> configuring fail2ban service...
2024/10/31 21:20:27 | stdout | => Enabling fail2ban service... because FAIL2BAN_ENABLED=true
2024/10/31 21:20:27 | stdout | ---> fixing permissions: '/var/spool/cron'
2024/10/31 21:20:27 | stdout | --> configuring cron service...
2024/10/31 21:20:27 | stdout | => Enabling cron service... because CRON_ENABLED=true
2024/10/31 21:20:27 | stdout | => Disabling postfix service... because POSTFIX_ENABLED=false
2024/10/31 21:20:27 | stdout | --> forwarding all emails to:
2024/10/31 21:20:27 | stdout | => Setting up MSMTP as (default) sendmail replacement
2024/10/31 21:20:27 | stdout | ln: failed to create symbolic link '/tftpboot': File exists
2024/10/31 21:20:27 | stdout | ---> WARNING: file or directory doesn't exist: '/var/lib/tftpboot'
2024/10/31 21:20:27 | stdout | --> verifying files permissions
2024/10/31 21:20:27 | stdout | => WARNING: No Persistent storage path detected... the configurations will be lost on container restart
2024/10/31 21:20:27 | stdout | ---> RHEL Linux based distro detected
2024/10/31 21:20:27 | stdout | --> fixing supervisord config file...
2024/10/31 21:20:27 | stdout | --> Custom Script Hooks: OFF
2024/10/31 21:20:27 | stdout | => Executing izpbx-asterisk hooks:
2024/10/31 21:20:27 | stdout | ===============================================================================
2024/10/31 21:20:27 | stdout | => Starting container izPBX Cloud Native Telephony System -> izpbx-asterisk:20.16.16 (build:128 commit:ba5b039 date:2024-08-09)
2024/10/31 21:18:44 | stdout | ---> WARNING: unable to access asterisk database. Please check if exist and the permissions... exiting
2024/10/31 21:18:44 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:44 | stdout | ---> START install FreePBX @ Thu Oct 31 20:18:44 UTC 2024
2024/10/31 21:18:44 | stdout | --> installing FreePBX in '/var/www/html'
2024/10/31 21:18:44 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:44 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[10/10]
2024/10/31 21:18:44 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:38 | stdout | /usr/sbin/safe_asterisk: line 171:  1283 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:34 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[9/10]
2024/10/31 21:18:34 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:32 | stdout | /usr/sbin/safe_asterisk: line 171:  1204 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:26 | stdout | /usr/sbin/safe_asterisk: line 171:  1125 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:24 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[8/10]
2024/10/31 21:18:24 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:19 | stdout | /usr/sbin/safe_asterisk: line 171:  1048 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:14 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[7/10]
2024/10/31 21:18:14 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:13 | stdout | /usr/sbin/safe_asterisk: line 171:   969 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:07 | stdout | /usr/sbin/safe_asterisk: line 171:   892 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:18:04 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[6/10]
2024/10/31 21:18:04 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:18:00 | stdout | /usr/sbin/safe_asterisk: line 171:   813 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:54 | stdout | /usr/sbin/safe_asterisk: line 171:   734 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:54 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[5/10]
2024/10/31 21:17:54 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:17:48 | stdout | /usr/sbin/safe_asterisk: line 171:   657 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:43 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[4/10]
2024/10/31 21:17:43 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:17:41 | stdout | /usr/sbin/safe_asterisk: line 171:   578 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:35 | stdout | /usr/sbin/safe_asterisk: line 171:   499 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:33 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[3/10]
2024/10/31 21:17:33 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:17:29 | stdout | /usr/sbin/safe_asterisk: line 171:   422 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:23 | stdout | --> WARNING: cannot connect to MySQL database 'db'... waiting database to become ready... retrying in 10 seconds... try:[2/10]
2024/10/31 21:17:23 | stdout | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)
2024/10/31 21:17:22 | stdout | /usr/sbin/safe_asterisk: line 171:   343 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:16 | stdout | /usr/sbin/safe_asterisk: line 171:   266 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:13 | stdout | Asterisk Started
2024/10/31 21:17:10 | stdout | /usr/sbin/safe_asterisk: line 171:   181 Illegal instruction     (core dumped) nice -n $PRIORITY "${ASTSBINDIR}/asterisk" -f ${CLIARGS} ${ASTARGS} > /dev/null 2>&1 < /dev/null
2024/10/31 21:17:07 | stdout | STARTING ASTERISK
2024/10/31 21:17:07 | stdout |  
2024/10/31 21:17:07 | stdout |  
2024/10/31 21:17:07 | stdout | --> NOTE: skipping MySQL init because not root user password defined
2024/10/31 21:17:07 | stdout | --> missing '/.initialized' file... initializing FreePBX... try:[1/5]
2024/10/31 21:17:07 | stdout | =====================================================================
2024/10/31 21:17:07 | stdout | => !!! NEW INSTALLATION DETECTED :: FreePBX IS NOT INITIALIZED !!! <=
2024/10/31 21:17:07 | stdout | =====================================================================
2024/10/31 21:17:07 | stdout |  
2024/10/31 21:17:07 | stdout | ---> configuring FreePBX ODBC
2024/10/31 21:17:07 | stdout | ---> verifing FreePBX configurations
2024/10/31 21:17:07 | stdout | --> configuring izpbx service...
2024/10/31 21:17:07 | stdout | => Enabling izpbx service... because IZPBX_ENABLED=true
2024/10/31 21:17:07 | stdout | => Disabling asterisk service... because ASTERISK_ENABLED=false
2024/10/31 21:17:07 | stdout | --> configuring Apache VirtualHosting and creating empty /etc/httpd/conf.d/virtual.conf file
2024/10/31 21:17:07 | stdout | --> setting Apache ServerName to izPBX
2024/10/31 21:17:07 | stdout | --> configuring httpd service...
2024/10/31 21:17:07 | stdout | => Enabling httpd service... because HTTPD_ENABLED=true
2024/10/31 21:17:07 | stdout | --> reconfiguring Fail2ban settings...
2024/10/31 21:17:07 | stdout | --> configuring fail2ban service...
2024/10/31 21:17:07 | stdout | => Enabling fail2ban service... because FAIL2BAN_ENABLED=true
2024/10/31 21:17:07 | stdout | ---> fixing permissions: '/var/spool/cron'
2024/10/31 21:17:07 | stdout | --> configuring cron service...
2024/10/31 21:17:07 | stdout | => Enabling cron service... because CRON_ENABLED=true
2024/10/31 21:17:07 | stdout | => Disabling postfix service... because POSTFIX_ENABLED=false
2024/10/31 21:17:07 | stdout | --> forwarding all emails to:
2024/10/31 21:17:07 | stdout | => Setting up MSMTP as (default) sendmail replacement
2024/10/31 21:17:07 | stdout | ---> WARNING: file or directory doesn't exist: '/var/lib/tftpboot'
2024/10/31 21:17:07 | stdout | --> verifying files permissions
2024/10/31 21:17:07 | stdout | => WARNING: No Persistent storage path detected... the configurations will be lost on container restart
2024/10/31 21:17:07 | stdout | ---> RHEL Linux based distro detected
2024/10/31 21:17:07 | stdout | --> fixing supervisord config file...
2024/10/31 21:17:07 | stdout | --> Custom Script Hooks: OFF
2024/10/31 21:17:07 | stdout | => Executing izpbx-asterisk hooks:
2024/10/31 21:17:07 | stdout | ===============================================================================
2024/10/31 21:17:07 | stdout | => Starting container izPBX Cloud Native Telephony System -> izpbx-asterisk:20.16.16 (build:128 commit:ba5b039 date:2024-08-09)

**Comment by ugoviti** [comment]
Have you solved that problem?
